title: Venkatesh R
Logo: C:\Users\DELL\Downloads\Head_Shot.jpg
Description: Experienced Analyst with over two years in support, system administration, and configuration across organizations like Amazon, Enstoa, Infosys, and Altera Digital Health. Proficient in tools such as Oracle Unifier, Apache Tomcat, and ServiceNow, with strong SQL skills for data analysis and issue resolution. Known for ensuring SLA compliance, streamlining processes, and delivering reliable technical solutions. A quick learner with a strong focus on problem-solving, client satisfaction, and continuous improvement.
show_downloads: true
theme: jekyll-theme-minimal


